// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-ce-P9F0GuGKCh6ZQ9Fx6Fn6yeTmvwM',
    appId: '1:454999399231:web:306d2d13a3f45f7465918a',
    messagingSenderId: '454999399231',
    projectId: 'aeka-ustaad',
    authDomain: 'aeka-ustaad.firebaseapp.com',
    storageBucket: 'aeka-ustaad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2vQFggfdHZrKFYKQ722p7reptk6ldGgs',
    appId: '1:454999399231:android:a6b9c601ee65b74265918a',
    messagingSenderId: '454999399231',
    projectId: 'aeka-ustaad',
    storageBucket: 'aeka-ustaad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6I8NoZ-QsaFtNeT5RNTsW2kZaTTKRkx8',
    appId: '1:454999399231:ios:d571c5f7339e052565918a',
    messagingSenderId: '454999399231',
    projectId: 'aeka-ustaad',
    storageBucket: 'aeka-ustaad.firebasestorage.app',
    iosBundleId: 'com.example.centuryAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6I8NoZ-QsaFtNeT5RNTsW2kZaTTKRkx8',
    appId: '1:454999399231:ios:d571c5f7339e052565918a',
    messagingSenderId: '454999399231',
    projectId: 'aeka-ustaad',
    storageBucket: 'aeka-ustaad.firebasestorage.app',
    iosBundleId: 'com.example.centuryAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW-ce-P9F0GuGKCh6ZQ9Fx6Fn6yeTmvwM',
    appId: '1:454999399231:web:d360adbc9e9841de65918a',
    messagingSenderId: '454999399231',
    projectId: 'aeka-ustaad',
    authDomain: 'aeka-ustaad.firebaseapp.com',
    storageBucket: 'aeka-ustaad.firebasestorage.app',
  );
}
